name: first-workflow
on: [push]
jobs:
  shell-cmd-job:
    runs-on: ubuntu-lastest
    steps:
      - name: echo Hello
        run: echo "Hello World"
      - name: multiple line cmd
        run: |
          node -v
          npm -v